Task description:

**Case Study: Engine Breakdown Risk – Backend + Analytics + Tableau**

You are part of the BI &amp; Analytics team responsible for monitoring and predicting engine
breakdown risk. Senior management wants a reliable backend data foundation and a clear
Tableau dashboard that explains the drivers of breakdowns and supports proactive decision-
making.
You are given a dataset of historical engine operation records. Your task is to:
1. Design the backend data model and transformations needed to support analysis and
dashboards.
2. Analyze the data and identify patterns related to the target variable breakdown.
3. Propose or build a predictive approach for estimating breakdown risk.
4. Create a Tableau dashboard that communicates insights to senior management. (twbx)
5. Prepare a short presentation summarizing your findings, insights, and
recommendations. (ppt)

## Imports and functions

In [30]:
import pandas as pd
from io import StringIO

In [31]:
def read_input_file(file_path):
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    content = "\n".join(
        line.strip('"') for line in content.splitlines()
    )

    df = pd.read_csv(
        StringIO(content),
        sep=","
    )
    return df

## Input table description

| Column | Description | Values / Meaning |
|---|---|---|
| `oph` | Operating hours of the engine | — |
| `pist_m` | Piston material | — |
| `issue_type` | Combustion issue type | `1` = typical issue<br>`2` = atypical issue<br>`3` = non-related<br>`4` = non-symptomatic |
| `bmep` | Brake mean effective pressure (average pressure forcing the pistons down) | — |
| `ng_imp` | Natural gas impurities (nmol) | — |
| `past_dmg` | Engine had past damages | `1` = true<br>`0` = false |
| `resting_analysis_results` | Resting results after operation | `0` = normal<br>`1` = abnormal<br>`2` = critical |
| `rpm_max` | Maximum rotations per minute achieved | — |
| `full_load_issues` | Issues induced due to full load operation | `1` = yes<br>`0` = no |
| `number_up` | Number of unplanned events | — |
| `number_tc` | Number of installed turbochargers | — |
| `op_set_1` | Operational engine setting 1 | — |
| `op_set_2` | Operational engine setting 2 | — |
| `op_set_3` | Operational engine setting 3 | — |
| `breakdown` | Breakdown probability indicator | `0` = less chance of breakdown<br>`1` = more chance of breakdown |

## File read in

In [32]:
FILE_PATH = "./data/BI Fullstack case study dataset.csv"
df = read_input_file(FILE_PATH)
df

,engine_id,timestamp,oph,pist_m,issue_type,bmep,ng_imp,past_dmg,resting_analysis_results,rpm_max,full_load_issues,number_up,number_tc,op_set_1,op_set_2,op_set_3,breakdown
0,ENG001,2021-02-14,5120,2,1,14.8,210,0,0,1485,0.0,1.0,1.0,0.81,0.76,0.88,0.0
1,ENG001,2021-06-22,8450,1,2,17.2,260,1,1,1530,1.0,3.0,2.0,0.84,0.79,0.91,1.0
2,ENG001,2022-01-09,3920,3,1,13.1,150,0,0,1440,0.0,0.0,1.0,0.74,0.78,0.82,0.0
3,ENG001,2022-08-17,10210,2,4,18.4,320,1,2,1585,1.0,4.0,2.0,0.89,0.83,0.94,1.0
4,ENG001,2023-03-11,7210,1,3,12.7,140,0,1,1425,0.0,2.0,1.0,0.72,0.75,0.80,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,ENG050,2023-03-24,6720,3,3,13.2,160,0,1,1445,0.0,2.0,1.0,0.74,0.78,0.82,0.0
497,ENG050,2023-07-11,10280,1,4,17.8,320,1,2,1580,1.0,4.0,2.0,0.88,0.83,0.94,1.0
498,ENG050,2023-11-03,4950,2,1,13.9,170,0,0,1460,0.0,1.0,1.0,0.76,0.79,0.84,0.0
499,ENG050,2024-03-29,9100,3,2,17.0,275,1,1,1510,1.0,3.0,2.0,0.83,0.78,0.90,1.0
500,ENG050,2024-11-16,3160,1,3,12.4,135,0,0,1395,0.0,0.0,1.0,0.70,0.72,0.77,0.0

## Sanity checks

### Check for unique values

In [33]:
for col in df.columns:
    print(col)
    print(df[col].unique())
    print()

engine_id
<StringArray>
['ENG001', 'ENG002', 'ENG003', 'ENG004', 'ENG005', 'ENG006', 'ENG007',
 'ENG008', 'ENG009', 'ENG010', 'ENG011', 'ENG012', 'ENG013', 'ENG014',
 'ENG015', 'ENG016', 'ENG017', 'ENG018', 'ENG019', 'ENG020', 'ENG021',
 'ENG022', 'ENG023', 'ENG024', 'ENG025', 'ENG026', 'ENG027', 'ENG028',
 'ENG029', 'ENG030', 'ENG031', 'ENG032', 'ENG033', 'ENG034', 'ENG035',
 'ENG036', 'ENG037', 'ENG038', 'ENG039', 'ENG040', 'ENG041', 'ENG042',
 'ENG043', 'ENG044', 'ENG045', 'ENG046', 'ENG047', 'ENG048', 'ENG049',
 'ENG050']
Length: 50, dtype: str

timestamp
<StringArray>
['2021-02-14', '2021-06-22', '2022-01-09', '2022-08-17', '2023-03-11',
 '2023-11-28', '2024-04-19', '2024-07-03', '2024-09-15', '2024-12-06',
 ...
 '2022-02-02', '2022-06-06', '2022-12-02', '2023-10-13', '2024-03-23',
 '2024-09-12', '2022-12-13', '2023-03-24', '2023-07-11', '2024-03-29']
Length: 423, dtype: str

oph
[ 5120  8450  3920 10210  7210 11890  2680 13450  9050  4820 10980  5400
  7800  3150 12840  6550  9950  4550  8750  2890 11850  5250  7650  3300
 13020  6620 10150  4750  8920  3020 12010  5520  8020  3450 13110  6700
 10220  4900  3100 11780  5380  7820  3250 12940  6600 10080  4700  8900
  2980 11920  5480  7920  3380 13080  6680 10120  4850  8970  3050 11860
  5330  7850  3220 12980  6580 10040  4800  8880  2940 12050  5560  8040
  3490 13140  6730 10260  4930  9080  3140 12110  5590  8080  3520 13200
  6750 10310  5010  9150  3190  5420  7840  3290 12960  6610 10090  4780
  8860  2920 12080  5510  8030  3460 13120  6690 10240  4890  9070  3120
 11970  5470  7910  3370 13070  6670 10110  4860  8940  3030 11840  5390
  7830  3240 12920  6570 10060  4790  8870  2930 12030  5500  8010  3440
 13100  4870  9060  3110 11910  5460  7900  3360 13060  6660  4840  8930
  3010 11820  5370  7810  3230 12900  6560  4770  8850  2910 11940  5450
  7890  3350 13040  6650 10070  4830  8960  3040 12060  5530  8050  3500
 13160  6720 10280  4950  9100  3160 11870  5410  7860  3270 12950  6590
 10030  8890  2960 11810  5360 12910 10020  4760  8840  2900 11930  5440
  7880  3340 13030  6640  8950 12070  5540  8060  3510 13170 10290  4960
  9110  3170  7870  3280  2970 11800  5350  6540 10010  8830 11950 13050
  5430 11980 12090  3260  4810  2950 12970 12040  5490  8000  3430 13090
 10200  9040  3090 12100 11990  8980  3060]

pist_m
[2 1 3]

issue_type
[1 2 4 3]

bmep
[14.8 17.2 13.1 18.4 12.7 19.1 11.8 19.3 17.  12.6 18.  14.2 16.3 13.3
 19.  13.  17.6 13.7 16.8 12.2 18.9 14.  16.4 13.4 19.2 17.7 13.8 17.1
 12.3 14.3 16.6 13.5 13.2 17.8 13.9 12.4 18.7 14.1 16.5 18.8 16.7]

ng_imp
[210 260 150 320 140 360 120 390 275 145 330 175 255 135 380 305 165 270
 130 365 170 155 315 280 370 265 395 160 355 385 310 375 180]

past_dmg
[0 1]

resting_analysis_results
[0 1 2]

rpm_max
[1485 1530 1440 1585 1425 1610 1385 1625 1505 1405 1590 1475 1495 1420
 1615 1445 1575 1455 1515 1395 1605 1470 1500 1620 1450 1520 1400 1600
 1480 1580 1460 1510]

full_load_issues
[ 0.  1. nan]

number_up
[ 1.  3.  0.  4.  2.  5.  6. nan]

number_tc
[ 1.  2. nan]

op_set_1
[0.81 0.84 0.74 0.89 0.72 0.91 0.68 0.93 0.83 0.73 0.77 0.82 0.71 0.92
 0.87 0.75 0.7  0.88 0.78 0.76 0.9   nan]

op_set_2
[0.76 0.79 0.78 0.83 0.75 0.86 0.71 0.87 0.77 0.84 0.8  0.74 0.82 0.72
 0.73 0.81 0.88 0.85  nan]

op_set_3
[0.88 0.91 0.82 0.94 0.8  0.96 0.76 0.97 0.89 0.81 0.85 0.79 0.93 0.84
 0.9  0.77 0.78 0.95  nan]

breakdown
[ 0.  1. nan]

### Check for Nan values

In [34]:
df[df.isna().any(axis=1)]

,engine_id,timestamp,oph,pist_m,issue_type,bmep,ng_imp,past_dmg,resting_analysis_results,rpm_max,full_load_issues,number_up,number_tc,op_set_1,op_set_2,op_set_3,breakdown
440,ENG045,2021-02-21,11990,2,2,18.9,365,1,2,1605,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Check for duplicates

In [35]:
df_non_duplicate = df.drop_duplicates()
len(df_non_duplicate) == len(df)

True

## Copy and Clean

In [36]:
df_copy = df.copy()
df_clean = df_copy.dropna()

### Change type and second check

In [37]:
df_clean['timestamp'] =pd.to_datetime(df_clean['timestamp']).dt.strftime('%Y-%m-%d')

int_columns = [
    'pist_m', 'issue_type', 'past_dmg', 'resting_analysis_results',
    'full_load_issues', 'number_up', 'number_tc', 'breakdown'
]

for col in int_columns:
    df_clean[col] = df_clean[col].astype(int)

print(df_clean.head())

  engine_id   timestamp    oph  pist_m  issue_type  bmep  ng_imp  past_dmg  \
0    ENG001  2021-02-14   5120       2           1  14.8     210         0
1    ENG001  2021-06-22   8450       1           2  17.2     260         1
2    ENG001  2022-01-09   3920       3           1  13.1     150         0
3    ENG001  2022-08-17  10210       2           4  18.4     320         1
4    ENG001  2023-03-11   7210       1           3  12.7     140         0

   resting_analysis_results  rpm_max  full_load_issues  number_up  number_tc  \
0                         0     1485                 0          1          1
1                         1     1530                 1          3          2
2                         0     1440                 0          0          1
3                         2     1585                 1          4          2
4                         1     1425                 0          2          1

   op_set_1  op_set_2  op_set_3  breakdown
0      0.81      0.76      0.88          0
1      0.84      0.79      0.91          1
2      0.74      0.78      0.82          0
3      0.89      0.83      0.94          1
4      0.72      0.75      0.80          0

In [38]:
for col in df_clean.columns:
    print(col)
    print(df_clean[col].unique())
    print()

engine_id
<StringArray>
['ENG001', 'ENG002', 'ENG003', 'ENG004', 'ENG005', 'ENG006', 'ENG007',
 'ENG008', 'ENG009', 'ENG010', 'ENG011', 'ENG012', 'ENG013', 'ENG014',
 'ENG015', 'ENG016', 'ENG017', 'ENG018', 'ENG019', 'ENG020', 'ENG021',
 'ENG022', 'ENG023', 'ENG024', 'ENG025', 'ENG026', 'ENG027', 'ENG028',
 'ENG029', 'ENG030', 'ENG031', 'ENG032', 'ENG033', 'ENG034', 'ENG035',
 'ENG036', 'ENG037', 'ENG038', 'ENG039', 'ENG040', 'ENG041', 'ENG042',
 'ENG043', 'ENG044', 'ENG045', 'ENG046', 'ENG047', 'ENG048', 'ENG049',
 'ENG050']
Length: 50, dtype: str

timestamp
<StringArray>
['2021-02-14', '2021-06-22', '2022-01-09', '2022-08-17', '2023-03-11',
 '2023-11-28', '2024-04-19', '2024-07-03', '2024-09-15', '2024-12-06',
 ...
 '2022-02-02', '2022-06-06', '2022-12-02', '2023-10-13', '2024-03-23',
 '2024-09-12', '2022-12-13', '2023-03-24', '2023-07-11', '2024-03-29']
Length: 423, dtype: str

oph
[ 5120  8450  3920 10210  7210 11890  2680 13450  9050  4820 10980  5400
  7800  3150 12840  6550  9950  4550  8750  2890 11850  5250  7650  3300
 13020  6620 10150  4750  8920  3020 12010  5520  8020  3450 13110  6700
 10220  4900  3100 11780  5380  7820  3250 12940  6600 10080  4700  8900
  2980 11920  5480  7920  3380 13080  6680 10120  4850  8970  3050 11860
  5330  7850  3220 12980  6580 10040  4800  8880  2940 12050  5560  8040
  3490 13140  6730 10260  4930  9080  3140 12110  5590  8080  3520 13200
  6750 10310  5010  9150  3190  5420  7840  3290 12960  6610 10090  4780
  8860  2920 12080  5510  8030  3460 13120  6690 10240  4890  9070  3120
 11970  5470  7910  3370 13070  6670 10110  4860  8940  3030 11840  5390
  7830  3240 12920  6570 10060  4790  8870  2930 12030  5500  8010  3440
 13100  4870  9060  3110 11910  5460  7900  3360 13060  6660  4840  8930
  3010 11820  5370  7810  3230 12900  6560  4770  8850  2910 11940  5450
  7890  3350 13040  6650 10070  4830  8960  3040 12060  5530  8050  3500
 13160  6720 10280  4950  9100  3160 11870  5410  7860  3270 12950  6590
 10030  8890  2960 11810  5360 12910 10020  4760  8840  2900 11930  5440
  7880  3340 13030  6640  8950 12070  5540  8060  3510 13170 10290  4960
  9110  3170  7870  3280  2970 11800  5350  6540 10010  8830 11950 13050
  5430 11980 12090  3260  4810  2950 12970 12040  5490  8000  3430 13090
 10200  9040  3090 12100 11990  8980  3060]

pist_m
[2 1 3]

issue_type
[1 2 4 3]

bmep
[14.8 17.2 13.1 18.4 12.7 19.1 11.8 19.3 17.  12.6 18.  14.2 16.3 13.3
 19.  13.  17.6 13.7 16.8 12.2 18.9 14.  16.4 13.4 19.2 17.7 13.8 17.1
 12.3 14.3 16.6 13.5 13.2 17.8 13.9 12.4 18.7 14.1 16.5 18.8 16.7]

ng_imp
[210 260 150 320 140 360 120 390 275 145 330 175 255 135 380 305 165 270
 130 365 170 155 315 280 370 265 395 160 355 385 310 375 180]

past_dmg
[0 1]

resting_analysis_results
[0 1 2]

rpm_max
[1485 1530 1440 1585 1425 1610 1385 1625 1505 1405 1590 1475 1495 1420
 1615 1445 1575 1455 1515 1395 1605 1470 1500 1620 1450 1520 1400 1600
 1480 1580 1460 1510]

full_load_issues
[0 1]

number_up
[1 3 0 4 2 5 6]

number_tc
[1 2]

op_set_1
[0.81 0.84 0.74 0.89 0.72 0.91 0.68 0.93 0.83 0.73 0.77 0.82 0.71 0.92
 0.87 0.75 0.7  0.88 0.78 0.76 0.9 ]

op_set_2
[0.76 0.79 0.78 0.83 0.75 0.86 0.71 0.87 0.77 0.84 0.8  0.74 0.82 0.72
 0.73 0.81 0.88 0.85]

op_set_3
[0.88 0.91 0.82 0.94 0.8  0.96 0.76 0.97 0.89 0.81 0.85 0.79 0.93 0.84
 0.9  0.77 0.78 0.95]

breakdown
[0 1]

## Export